// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace demoWML.Models;

public partial class AccountPhoneNumber
{
    public Guid Id { get; set; }

    public Guid AccountId { get; set; }

    public byte PhoneNumberType { get; set; }

    public string PhoneNumber { get; set; } = null!;

    public string? PhoneExtension { get; set; }

    public virtual Account Account { get; set; } = null!;
}