// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace demoWML.Models;

public partial class Account
{
    public Guid Id { get; set; }

    public string Username { get; set; } = null!;

    public string HashPassword { get; set; } = null!;

    public string LastName { get; set; } = null!;

    public string FirstName { get; set; } = null!;

    public byte AccountStatus { get; set; }

    public byte AccountType { get; set; }

    public DateTimeOffset? LastUpdatedTime { get; set; }

    public virtual ICollection<AccountPhoneNumber> AccountPhoneNumbers { get; set; } = new List<AccountPhoneNumber>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}