// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace demoWML.Models;

public partial class AdmissionRecord
{
    public Guid Id { get; set; }

    public Guid TicketId { get; set; }

    public Guid MuseumId { get; set; }

    public DateTimeOffset RecordTime { get; set; }

    public bool IsRejected { get; set; }

    public virtual Museum Museum { get; set; } = null!;

    public virtual Ticket Ticket { get; set; } = null!;
}