// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace demoWML.Models;

public partial class Museum
{
    public Guid Id { get; set; }

    public long OsmId { get; set; }

    public string Name { get; set; } = null!;

    public string CountryCode { get; set; } = null!;

    public string City { get; set; } = null!;

    public string Street { get; set; } = null!;

    public decimal Latitude { get; set; }

    public decimal Logitude { get; set; }

    public string? Website { get; set; }

    public string? Description { get; set; }

    public virtual ICollection<AdmissionRecord> AdmissionRecords { get; set; } = new List<AdmissionRecord>();
}