// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace demoWML.Models;

public partial class Order
{
    public Guid Id { get; set; }

    public Guid AccountId { get; set; }

    public string OrderNumber { get; set; } = null!;

    public decimal Amount { get; set; }

    public decimal Discount { get; set; }

    public decimal TotalAmount { get; set; }

    public DateTimeOffset? PaidTime { get; set; }

    public DateTimeOffset CreatedTime { get; set; }

    public virtual Account Account { get; set; } = null!;

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}