// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace demoWML.Models;

public partial class Ticket
{
    public Guid Id { get; set; }

    public Guid OrderId { get; set; }

    public string? Number { get; set; }

    public string? LastName { get; set; }

    public string? FirstName { get; set; }

    public byte Age { get; set; }

    public DateTimeOffset? EffectiveTimeStart { get; set; }

    public DateTimeOffset? EffectiveTimeLastActivateFrom { get; set; }

    public DateTimeOffset? EffectiveTimeEnd { get; set; }

    public decimal Amount { get; set; }

    public byte AppliedAgeType { get; set; }

    public byte AppliedDurationType { get; set; }

    public virtual ICollection<AdmissionRecord> AdmissionRecords { get; set; } = new List<AdmissionRecord>();

    public virtual Order Order { get; set; } = null!;
}